### ISSUE TITLE
Type predicates break TypeScript semantics (PR #457)

### ISSUE THREAD

**Issue by PoByBolek** [js-joda/js-joda#546]
The changes introduced in #457 break TypeScript semantics because `.equals()` isn't really a type predicate. Just because two temporals are unequal to each other doesn't mean that the other one has a different type.

Simple example:
```typescript
function issue(): void {
    const today = LocalDate.now();
    const someday = LocalDate.of(2021, 9, 20);
    if (today.equals(someday)) {
        console.log(someday.year());
    } else {
        // This now raises a compiler error because TypeScript thinks that
        // someday has type never.
        // error TS2339: Property 'year' does not exist on type 'never'.
        console.log(someday.year());
    }
}
```

**Comment by pithu** [comment]
Hello @PoByBolek Thanks for using js-joda and for reporting this issue.

Sounds reasonable, looks like this is a bug, @InExtremaRes any comments on this ?

**Comment by InExtremaRes** [comment]
Yes I think the report is totally correct. I can send a PR fixing this by tomorrow.
